# Generated by Django 2.0.7 on 2019-08-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngine', '0003_search_viewname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('Email', models.TextField(max_length=100)),
                ('Message', models.TextField(max_length=100)),
            ],
        ),
    ]
